# Generated by Django 3.0.5 on 2021-02-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
