# Generated by Django 3.0.5 on 2021-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210222_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('conf_code', models.CharField(max_length=62, verbose_name='confirmation code')),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
