# Generated by Django 3.0.5 on 2021-02-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_tempauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
