# Generated by Django 3.0.5 on 2021-03-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория'},
        ),
    ]
