# Generated by Django 3.0.5 on 2021-03-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210301_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['year'], 'verbose_name': 'Произведение'},
        ),
    ]
