# Generated by Django 3.0.5 on 2021-03-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210301_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['category'], 'verbose_name': 'Произведение'},
        ),
    ]
