# Generated by Django 3.0.5 on 2021-03-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210301_1903'),
        ('api', '0026_auto_20210301_1322'),
    ]

    operations = [
    ]
