# Generated by Django 3.0.5 on 2021-03-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20210302_1417'),
        ('api', '0042_auto_20210302_1202'),
    ]

    operations = [
    ]
